### ISSUE TITLE
Capacitor_Tantalum_SMD_US_Handsoldering_AKL.pretty — kopia should be Capacitor_Tantalum_SMD_US_Handsoldering_AKL.pretty

### ISSUE THREAD

**Issue by uzytkownik** [DawidCislo/Alternate-KiCad-Library#13]
It looks like it changed name since 3.0 release.

**Comment by DawidCislo** [comment]
Fixed with [517624c](https://github.com/DawidCislo/Alternate-KiCad-Library/commit/517624c99a770f77fa3f5738428e1938660a604b)
Fix will be released to the PCM in  te upcoming 4.0 version which is coming within weeks.
Thank you.
