### ISSUE TITLE
Incorrect pinout for Op Amp AD8041

### ISSUE THREAD

**Issue by rsimpson-dstl** [DawidCislo/Alternate-KiCad-Library#14]
The input pins for the AD8041 op-amp are inverted.

According to the datasheet and the example in my breadboard, inverting input is pin 2 and non-inverting is pin 3.  In Amplifier_Operational_AKL.kicad_sym they are the other way round.

**Comment by DawidCislo** [comment]
Fixed with https://github.com/DawidCislo/Alternate-KiCad-Library/commit/2fa964125e41bb6e0d2dbe71ce43db888dcddaca
