### ISSUE TITLE
Missing Crystal Symbole Lib

### ISSUE THREAD

**Issue by jeff25** [DawidCislo/Alternate-KiCad-Library#4]
Hi,

seems the Symbol libs are not compleate. For example Footprint for Crystal is exitsing but symbol libis missing,

br,
robert

**Comment by DawidCislo** [comment]
Crystal symbol library is planned to be added in the future. Use the generic crystal symbol in the "Device" library provided with KiCad, then assign footprints from AKL crystal footprint library as a workaround. Same applies to some other footprints.

This library is not even close to being "complete" and work is underway to add new symbols and footprints. Please keep in mind that updates are delivered in batches (1.0, 2.0, 3.0 etc.) and lack of frequent updates does not mean that no work is being made (although I do admit the progress is slow).

Thank you for your patience.

**Comment by jeff25** [comment]
Thanks for the quick answere. Happy to use your lib and waitig for further updates :-)

**Comment by DawidCislo** [comment]
Release candidate for V4 is out, for now only on GitHub, it has a crystal symbol library, as requested.
