### ISSUE TITLE
KiCad Package and Content Manager adds "PCM_" prefix automatically

### ISSUE THREAD

**Issue by ONLYA** [DawidCislo/Alternate-KiCad-Library#5]
I noticed that the library installed via KiCad 7's Package and Content Manager will have `PCM_` as the prefix of every footprint library. Could you please change the symbol-footprint binding for the kicad manager release?

**Comment by ONLYA** [comment]
I think there is the same issue for KiCad 6.

**Comment by ONLYA** [comment]
Thank you. I eventually removed all "PCM_" prefix from all the library names. This is such an unexpected behaviour. Hope there is a KiCad version detection condition to retrieve the package accordingly.

**Comment by bohrh** [comment]
You can clear this prefix. See Screenshot.
After the next start the added Footprintlibraries will show up w/o the prefix
You can find the setting also in file kicad.json

![image](https://user-images.githubusercontent.com/37756573/233740860-162232e9-fdba-42f8-acc4-69c0e438d7c9.png)
![image](https://user-images.githubusercontent.com/37756573/233741384-d1923566-a57a-428d-b48e-e24e0802151c.png)
![image](https://user-images.githubusercontent.com/37756573/233741612-09a7b07a-ead5-4d38-9c83-d82f9e0d5d13.png)

**Comment by ONLYA** [comment]
Cheers. This will solve my problem and also for people who know it. Actually, I found the `kicad.json` file and tried to modify it, which failed in my case. I think we definitely should change the "Preferences" instead.
However, I think this still needs to be solved for the users who just appear to install and use this library. This is more likely to be the initial configuration problem from the KiCad source.

**Comment by DawidCislo** [comment]
As of now I'm considering writing a script to bulk edit all the symbol libraries in a way to add PCM_ prefixes to all footprint links in the PCM release, but still leave the default behavior for people downloading the library through github. This way people using the PCM will have a seamless experience and people installing manually will not have any new issues.
As for now either renaming all footprint library aliases or changing preferences is the only workaround.

**Comment by imyaFamiliev** [comment]
> You can clear this prefix. See Screenshot. After the next start the added Footprintlibraries will show up w/o the prefix You can find the setting also in file kicad.json
> 
> ![image](https://user-images.githubusercontent.com/37756573/233740860-162232e9-fdba-42f8-acc4-69c0e438d7c9.png) ![image](https://user-images.githubusercontent.com/37756573/233741384-d1923566-a57a-428d-b48e-e24e0802151c.png) ![image](https://user-images.githubusercontent.com/37756573/233741612-09a7b07a-ead5-4d38-9c83-d82f9e0d5d13.png)

Thanks! It really helps!
@DawidCislo 
Maybe it easier to add  attention message in plugin download dialog page to remove library nickname prefix in setting before install AKL ?
![Screenshot 2024-03-11 195024](https://github.com/DawidCislo/Alternate-KiCad-Library/assets/45656206/b4c6f061-6ab7-4bdf-9c75-c686e073dd94)

**Comment by DawidCislo** [comment]
The current description in the PCM is a bit outdated, it was written when KiCad 6 was new, and had no such issues. It still points users to the website or github, that has the up-to-date instructions on how to remove the prefix from preferences before downloading, and how to rename all the footprint libraries on how to properly rename all the libraries.

**Comment by DawidCislo** [comment]
Every change to the metadata file has to be reviewed manually by the KiCad devs and I don't want to "spam" them with non-consequential updates to the description.

**Comment by DawidCislo** [comment]
With the release of AKL 4.0, this issue is fixed - newest version 4.0.1 correctly handles the PCM_ prefix, and for people that don't want any prefixes there's the 4.0 version that works without prefixes.
